CREATE TABLE Users (
    id INT GENERATED BY DEFAULT AS IDENTITY, 
    email VARCHAR UNIQUE NOT NULL, 
    hashed_password VARCHAR(255) NOT NULL, 
    firstname VARCHAR(255) NOT NULL, 
    lastname VARCHAR(255) NOT NULL
); 